name: PR Gatekeeper

on:
    pull_request:
    #     branches:
    #        - main
    workflow_dispatch:

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR
              run: |
                   echo "Merging into branch: ${GITHUB_BASE_REF}"
                   echo "PR Number: ${{ github.event.pull_request.number }}"
                   echo "Gatekeeper checks complete"

